version: "3.9"
services:
  telegram-bot:
    build: .
    environment:
      OVERSEERR_API_URL: "http://YOUR_IP_ADDRESS:5055/api/v1"
      OVERSEERR_API_KEY: "YOUR_OVERSEERR_API_KEY"
      TELEGRAM_TOKEN: "YOUR_TELEGRAM_TOKEN"
      PASSWORD: "YOUR_PASSWORD" # or "" for no access control
    volumes:
      - ./data:/app/data
    restart: unless-stopped